### ISSUE TITLE
creating a project

### ISSUE THREAD

**Issue by jacobjcastaneda** [projectmgr/projectmanager-sdk-python#11]
Hello there,

I'm trying to work with this API and as a part of that I was testing my understanding by trying to create a project. I attempted to do so with the following steps:

1. connect to PM client
2. create a new project with the `ProjectCreateDto`
3. provide `ProjectCreateDto` to the `create_project` method under the `projectClient` object (aka. `client.project.create_project(**kwargs)`)

I am getting an error that the `body` argument provided to `projectClient.create_project()` cannot be converted to json. I tried just providing the `ProjectCreateDto` dict and that also didn't work. Notably, when I invoke the `to_dict()` method under the `ProjectCreateDto` object, I also get errors that the dataclass object has no  `asdict()`method (though I know it does from `dataclass` documentation.)

Please help if you can.

**Comment by tspence** [comment]
Updating our example files for this now, thanks for the report!

**Comment by tspence** [comment]
#12 should fix

**Comment by jacobjcastaneda** [comment]
Thanks! Works great. In the future, do you prefer issues reported here or on the developer site?

**Comment by tspence** [comment]
Awesome!  To be honest all the best practices I see suggest reporting issues here, I must have just missed the notification for this issue report.

**Comment by tspence** [comment]
Closing - please feel free to report more here if you like!
