### ISSUE TITLE
create_many_tasks bug

### ISSUE THREAD

**Issue by jacobjcastaneda** [projectmgr/projectmanager-sdk-python#13]
Hi there,

The `create_many_tasks` method under the tasks client has a bug. Specifically, `dataclasses.asdict(body)` is called the same as in the case of a single task; however, body is of type `list` in this method so it does not work. 

Jacob

**Comment by jacobjcastaneda** [comment]
Also,

`taskAssignee` methods are not working due to this similar logic of collecting `body` as a list and the subsequent conversion of these elements to json. Please review.

jacob

**Comment by tspence** [comment]
Thanks, investigating

**Comment by tspence** [comment]
Fix is up for R103 patch is #14 ; will deploy as soon as R103 goes up
