### ISSUE TITLE
TypeError: ResourceDto.__init__() got an unexpected keyword argument 'createdDate'

### ISSUE THREAD

**Issue by jamescavanagh** [projectmgr/projectmanager-sdk-python#19]
Hello, 

Seems like the API got updated and there's a missing field. Should be a real easy fix, and will be forking the repo to get it done. 

I. I am running the API, attempting to query resources with the following line: 

resources_response = client.resource.query_resources(None, None, None, None, None)

I expect it to return an AstroResult list of resources. 

II. Unfortunately, I get the following error

TypeError: ResourceDto.__init__() got an unexpected keyword argument 'createdDate'

A search of the source code reveals that the ResourceDto class does not have this attribute

https://github.com/projectmgr/projectmanager-sdk-python/blob/4a060919f2b4a4a234cbf557a7ef5747e8aa502f/src/ProjectManagerSdk/models/resourcedto.py

III. Steps to reproduce 

import ProjectManagerSdk 

client = ProjectManagerSdk.projectmanagerclient.ProjectManagerClient('production','KCMDATAMESH')
client.with_api_key(apiKey)

resources_response = client.resource.query_resources(None, None, None, None, None)

**Comment by jamescavanagh** [comment]
Adding these attributes to the resourceDto class fixes the error

    createdDate: str | None = None
    createdBy: str | None = None
    modifiedDate: str | None = None
    modifiedBy: str | None = None

**Comment by tspence** [comment]
Thanks for catching this.  The Python SDK should not be throwing errors for new fields like this; we are shipping a R114 patch today that adds these fields.  The goal for the SDK should be - if a new release of the API starts sending a new field, and you're using an older version of the SDK, you shouldn't get an error for that.

We'll run some more tests to make sure this is being properly caught.  Thanks for the report!

**Comment by jamescavanagh** [comment]
It's no problem. It was benign in nature since it was pretty clear what the error was in terms of how API integration can go. 

Otherwise, the API has been straightforward to work with and this SDK is helpful.

**Comment by tspence** [comment]
I found that although I had updated parts of the code to use dacite, not every part did.  I updated the generator to replace ** with dacite, and it now handles regular addition of new fields correctly.
